name: manually build package for macos

on:
  workflow_dispatch:
    inputs:

      package-name:
        description: input the package name to be built
        required: true

      target-version:
        description: input a target version to be built
        required: false
        default: '14.0'

      target-arch:
        description: choose a target arch to be built for
        type: choice
        options:
          - x86_64
          - arm64

      build-type:
        description: choose a build type
        type: choice
        options:
          - release
          - debug

      link-type:
        description: choose a link type
        type: choice
        options:
          - static-most
          - shared-most
          - shared-full

      log-level:
        description: choose a log-level
        type: choice
        options:
          - ''
          - '-q'
          - '-v'
          - '-vv'

jobs:
  build:

    runs-on: macos-14

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/xcpkg/master/xcpkg
      - run: chmod a+x xcpkg
      - run: ./xcpkg setup
      - run: ./xcpkg update
      - run: ./xcpkg install MacOSX-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}/${{ github.event.inputs.package-name }} --link-type=${{ github.event.inputs.link-type }} ${{ github.event.inputs.log-level }}
      - run: ./xcpkg pack    MacOSX-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}/${{ github.event.inputs.package-name }} -o .

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package-name }}-macos${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}.tar.xz
          path: ${{ github.event.inputs.package-name }}-*.tar.xz
